name: flutter_multi_formatter
description: A package of formatters for international phone numbers, credit / debit cards and a masked formatter
version: 2.13.0
homepage: https://github.com/caseyryan/flutter_multi_formatter

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  # base58check: ^2.0.0
  # bech32: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter pub publish
# To format every file in directory use:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


